name: Test and Deploy to Render

on:
  push:
    branches:
      - main  # Adjust this to your desired branch

jobs:
  # Job 1: Run tests
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment (adjust the version if necessary)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use the appropriate Node.js version

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4: Run tests (Make sure you have tests in your project)
    - name: Run Tests
      run: npm run test  # This assumes your test script is `npm run test`

  # Job 2: Build and deploy (depends on the success of the test job)
  deploy:
    runs-on: ubuntu-latest
    needs: test  # This job will only run if the "test" job succeeds

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment (adjust the version if necessary)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use the appropriate Node.js version

    # Step 3: Install dependencies (you need this step again for the deploy job)
    - name: Install Dependencies
      run: npm install

    # Step 4: Build the project
    - name: Build Project
      run: npm run build

    # Step 5: Deploy to Render
    - name: Deploy to Render
      env:
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST \
        -H "Authorization: Bearer $RENDER_API_KEY" \
        -H "Content-Type: application/json" \
        --data '{"clearCache": true}' \
        https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys
